vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: /upload/event
            upload_destination: '%kernel.project_dir%/public/uploads/event'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_update: false
            delete_on_remove: true
